#ifndef FOVEALEXICAL_H
#define FOVEALEXICAL_H
#define VARIABLE "%(.*?)%"
#define APP_DESCRIPTION_REGEX "<description>(.*?)</description>"
#define APP_NAME_REGEX "<name>(.*?)</name>"
#define APP_ICON_URL_REGEX  "<icon>(.*?)</icon>"
#define APP_PROVIDER_REGEX "<provider>(.*?)</provider>"
#define APP_UPLOADED_BY_REGEX "<user>(.*?)</user>"
#define APP_VERSION "<version>(.*?)</version>"
#define APP_TASK "<do>(.*?)</do>"
#define SOURCE_URL "<src>(.*?)</src>"
#define APP_TASK_TEXTBOX "<textbox>(.*?)</textbox>"
#define APP_TASK_TEXTBOX_TITLE "<title>(.*?)</title>"
#define TITLE "<(h1|h2|h3)(.*?)>"
#define PARAGRAPH "<(p.*?)>"
#define MEDIA_URL "<media>(.*?)</media>"
#define VIDEO_URL "<video>(.*?)</video>"
#define DOWNLOAD_URL "<download>(.*?)</download>"
#define PALETTE_ID "<palette><name>(.*?)</name><icon>(.*?)</icon>"
#define APP_TASK_COMBOBOX "<combobox>(.*?)</combobox>"
#define APP_TASK_COMBOBOX_ITEMS "<opt>(.*?)</opt>"
#define TITLE_STYLE "title {(.*?)}"
#define PARAGRAPH_STYLE "body {(.*?)}"
#define OTHER_STYLE "other {(.*?)}"
#define FLOATS_STYLE "float-text {(.*?)}"
#define ALL_STYLE "all {(.*?)}"
#define BACKGROUND_LINK_STYLE "background-link: (.*?);"
#define BACKGROUND_FILE_STYLE "border-image: url\\((.*?)\\)"
#define ASPECT_RATIO "aspect-ratio: (.*?);"
#define FOVEA_DOC 0
#define FOVEA_TWO 1
#define FOVEA_CENTER 2
#define USER_RESULT_REGEX "<user>(.*?)</user><image>(.*?)</image>"
#define ACCOUNT_INFO_REGEX "<user>(.*?)</user><firstname>(.*?)</firstname><lastname>(.*?)</lastname><email>(.*?)</email><pic>(.*?)</pic>"
#define YOUTUBE_PLAYER ";ytplayer[.]config\\s*=\\s*([{].+?[}]);"
#define YOUTUBE_VIDEO_FORMATS "\\\\\"formats\\\\\":\\[.+?\\]"
#define YOUTUBE_VIDEO_URL "\\\\\"url\\\\\":(.+?)[,]"
#define REQUESTER "<requester>(.*?)</requester>"
#define REQUESTEE "<requestee>(.*?)</requestee>"
#define STATUS "<status>(.*?)</status>"
#endif // FOVEALEXICAL_H
